language: python
python:
  - "3.7"

services:
  - docker

before_script: pip install docker-compose

script: 
  - sudo chown -R $USER:$USER postgres-data/
  - docker-compose run web sh -c "python manage.py test && flake8"