version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_platform
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
  web:
    build: .
    command: sh -c "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration
  frontend:
    build:
      dockerfile: frontend/Dockerfile
      context: .
    volumes:
      - .:/app/
      - /frontend/node_modules
    ports:
      - "3000:3000"
  migration:
    build: .
    image: app
    command: bash -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput"
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db