# Generated by Django 2.2.7 on 2019-11-13 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='description',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='areas',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='areas',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Areas'),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sku',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='products',
            name='summary',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.PositiveIntegerField(null=True, unique=True)),
                ('total', models.FloatField(default=0.0)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.FloatField(default=0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Orders')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Products')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
